### ISSUE TITLE
I, as a cook, would love to be able to write a simple recipe list

### ISSUE THREAD

**Issue by gruenish** [nexus49/food-for-the-week#1]
Recipe list should contain:

Name of dish (mandatory)
URL to recipe page (optional)

{"recipes":[
    {"dishName":"Pirogge", "URL":""}, 
    {"dishName":"vegan oatmeal superbowl", "URL":"http://ohsheglows.com/2014/11/17/5-minute-oatmeal-power-bowl/"}, 
    {"dishName":"Tomato and Chickpea Curry", "URL":"http://www.oneingredientchef.com/chickpea-curry/"}, 
]}

**Comment by nexus49** [comment]
Check it out
